=== pelegrinalopezsem/REPOSITORIO-DE-APUNTES/LM/UNIDAD 1/EJERCICIOS/relacion4/relacion4-1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="100"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="autor">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z].*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="anioPublicacion">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1900"/>
                    <xs:maxInclusive value="2025"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="genero">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Novela"/>
                    <xs:enumeration value="PoesÃ­a"/>
                    <xs:enumeration value="Ensayo"/>
                    <xs:enumeration value="Teatro"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="isbn">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\d{3}-\d{2}-\d{4}-\d{3}-\d"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pelegrinalopezsem/REPOSITORIO-DE-APUNTES/LM/UNIDAD 1/EJERCICIOS/relacion4/relacion4-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="relacion4-1.xsd">
    <libro id="1">
        <titulo>Cien Años de Soledad</titulo>
        <autor>Gabriel Garcia Marquez</autor>
        <anioPublicacion>1967</anioPublicacion>
        <genero>Novela</genero>
        <isbn>978-84-3764-049-7</isbn>
    </libro>
    <libro id="2">
        <titulo>La Odisea</titulo>
        <autor>Homero</autor>
        <anioPublicacion>1995</anioPublicacion>
        <genero>Poesía</genero>
        <isbn>978-84-2494-049-2</isbn>
    </libro>
</biblioteca>
