=== pelegrinalopezsem/REPOSITORIO-DE-APUNTES/LM/UNIDAD 1/EJERCICIOS/repaso/ejercicio5.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agencia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paquete" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Destino" minOccurs="1" maxOccurs="unbounded">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                </xs:restriction>
                            </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                            </xs:element>
                            <xs:element name="fechaInicio" type="xs:date">
                            </xs:element>
                            <xs:element name="fechafin" type="xs:date">
                            </xs:element>
                            <xs:element name="tipo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Aventura"/>
                                    <xs:enumeration value="Relax"/>
                                    <xs:enumeration value="Cultural"/>
                                    <xs:enumeration value="Famiiliar"/>
                                </xs:restriction>
                            </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="PKT-[0-9]{4}">
                                    </xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Z][a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{8}[A-Z]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="18"/>
                                        <xs:maxExclusive value="99"></xs:maxExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9._%+-]+\.[a-zA-Z0-9._%+-]{2,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pelegrinalopezsem/REPOSITORIO-DE-APUNTES/LM/UNIDAD 1/EJERCICIOS/repaso/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<agencia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio5.xsd">

<paquete codigo="PKT-5555">
    <Destino>Maracena</Destino>
    <precio>88</precio>
    <fechaInicio>2025-09-10</fechaInicio>
    <fechafin>2025-09-23</fechafin>
    <tipo>Relax</tipo>
</paquete>
<cliente>
    <nombre>Sem</nombre>
    <dni>77022821F</dni>
    <edad>19</edad>
    <email>pelegrinalopezsem001.alu@stemgranada.com</email>
</cliente>
</agencia>
